# Documentation: https://rmk.rs/docs/configuration.html
[keyboard]
name = "u10e"
product_name = "u10e Keyboard on RMK"
vendor_id = 0x4c4b # rmk stock
product_id = 0x4747 # made up
usb_enable = true
board = "nice!nano"

[ble]
enabled = true
battery_adc_pin = "P0_04"
adc_divider_measured = 2000
adc_divider_total = 2806

[storage]
enabled = true
# Storage starts from 640K
start_addr = 0xA0000
# Storage uses 128K = 640K ~ 768K
num_sectors = 32

# [matrix] # Not valid for split
# # Row and col pins are mandatory
# row_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00"]
# col_pins = ["P0_31", "P0_29", "PO_02", "P1_15", "P1_13", "P1_11"]

# # RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# # row2col = true

[layout]
rows = 5
cols = 12
layers = 3

matrix_map = """
(0, 5, L)  (0, 4, L)  (0, 3, L)  (0, 2, L)  (0, 1, L)  (0, 0, L)    (0, 6, R)  (0, 7, R)  (0, 8, R)  (0, 9, R)  (0, 10, R)  (0, 11, R)
(1, 5, L)  (1, 4, L)  (1, 3, L)  (1, 2, L)  (1, 1, L)  (1, 0, L)    (1, 6, R)  (1, 7, R)  (1, 8, R)  (1, 9, R)  (1, 10, R)  (1, 11, R)
(2, 5, L)  (2, 4, L)  (2, 3, L)  (2, 2, L)  (2, 1, L)  (2, 0, L)    (2, 6, R)  (2, 7, R)  (2, 8, R)  (2, 9, R)  (2, 10, R)  (2, 11, R)
(3, 5, L)  (3, 4, L)  (3, 3, L)  (3, 2, L)  (3, 1, L)  (3, 0, L)    (3, 6, R)  (3, 7, R)  (3, 8, R)  (3, 9, R)  (3, 10, R)  (3, 11, R)
                                 (4, 2, L)  (4, 1, L)  (4, 0, L)    (4, 6, R)  (4, 7, R)  (4, 8, R)
"""

[split]
# split connection type
connection = "ble"

[split.central]
# Central's matrix definition and offsets
rows = 5
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
matrix_type = "normal"
row_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00"]
col_pins = ["P0_31", "P0_29", "PO_02", "P1_15", "P1_13", "P1_11"]


[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 6

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00"]
col_pins = ["P0_31", "P0_29", "PO_02", "P1_15", "P1_13", "P1_11"]
